version: '3.8'

services:
  books_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: books_app
    volumes:
      - ./app:/var/www/app
    depends_on:
      - books_pg

  books_nginx:
    image: nginx:latest
    container_name: books_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books_app

  books_pg:
    image: postgres:15
    container_name: books_pg
    restart: always
    environment:
      POSTGRES_DB: books_api
      POSTGRES_USER: books_api
      POSTGRES_PASSWORD: books_api
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: books_adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: